[app]
JwtSecret = 233

[server]
#debug or release
RunMode = debug
HttpPort = 8080
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = postgres
User = user
Password = password
; local test
Host = localhost
; deploy
; Host = postgres
Port = 5432
Name = mydatabase

[minio]
; local test
EndPoint = localhost:9000
; deploy
; EndPoint = minio:9000
AccessKeyID = minioadmin
SecretAccessKey = minioadmin
BucketName = mybucket