[app]
JwtSecret = 233

[server]
#debug or release
RunMode = debug
HttpPort = 8080
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = postgres
User = user
Password = password
Host = localhost
Port = 5432
Name = mydatabase

[minio]
EndPoint = localhost:9000
AccessKeyID = minioadmin
SecretAccessKey = minioadmin
BucketName = mybucket